# Use a Node.js image
FROM node:16-alpine

# Set the working directory
WORKDIR /frontend

# Copy package.json and package-lock.json to the working directory
COPY ./frontend/package.json ./frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . ./
RUN npm install axios
RUN npm install --save-dev @types/axios

# Expose the development port
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]