FROM python:3.12

# Set the working directory
WORKDIR /backend

RUN apt-get update && \
    apt-get install -y \
    curl \
    apt-transport-https \
    gnupg \
    ca-certificates && \
    # Add Microsoft's package signing key
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    # Add the Microsoft repository
    curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    # Update package list and install ODBC driver
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc 

COPY ./backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "backend.backend:app", "--host", "0.0.0.0", "--port", "8000"]
